### ISSUE TITLE
Bug: Admin Notification Emails Not Sent When Service Author Opts Out & Feature Request for Admin Notification Preferences

### ISSUE THREAD

**Issue by suzana-fqs** [arielkeybob/professional-referral-directory#6]
## Bug Description
When the author of a professional service does not check the "I wish to receive email notifications for this service" option, the administrators and additional email addresses specified in the plugin settings do not receive notifications. This unintended behavior means the notification preferences of service authors are affecting the notifications of administrators or other specified emails.

### Expected Behavior
Administrators and any emails listed in the plugin settings should receive a notification when a service is viewed in the frontend, regardless of the service author's choice.

### Current Behavior
No notifications are sent out when the service author unchecks the notification preference checkbox - not even to the administrators or other specified emails.

### Steps to Reproduce
1. Navigate to the 'Add New Service' post type in the dashboard.
2. Fill out the required information but leave the "I wish to receive email notifications for this service" checkbox unchecked.
3. Publish the service.
4. View the service on the frontend as a visitor.
5. Notice that no notification email is sent to the administrators or additional specified emails.

## Potential Impact
This issue critically impacts the site administrator's ability to monitor engagement with the listings, potentially affecting operational decisions and customer service.

## Proposed Solutions
1. *Immediate Fix:* Ensure that admin/notification emails are sent out independently of the service author's preferences.
2. *Feature Request - Admin Notification Preferences:* Allow administrators to select which services they want to receive notifications for, with the possibility to specify preferences by individual service, author, taxonomy, etc., enhancing plugin flexibility and management.

### Additional Suggestions
- Implement a global override in plugin settings to ensure admin notifications are always sent out, regardless of individual author preferences.
- Introduce a logging system for email notifications within the plugin for troubleshooting and ensuring delivery.

### Context (Environment)
- Plugin Version: e.g., 1.1
- WordPress Version: e.g., 6.4.3
- PHP Version: e.g., 8.1

Feedback and further suggestions to improve this functionality are highly welcomed.

**Comment by arielkeybob** [comment]
Hello,

First off, I want to thank you for bringing this issue to our attention and for the detailed suggestions on improving the notification functionality of our plugin. We acknowledge the critical nature of the issue you've highlighted and are committed to ensuring that administrators and emails specified in the settings receive notifications, regardless of the service author's preferences.

### Action Plan

1. **Immediate Fix:** 
    - We will work on an update to decouple the notification preferences of authors from the notifications sent to administrators and the emails defined in the plugin settings. This will ensure that critical notifications are not missed.

2. **Development of New Features:**
    - **Notification Preferences for Administrators:** We are excited about the idea of allowing administrators to customize their notification preferences. We will assess the best way to implement this feature, considering granularity options by service, author, and taxonomy.
    - **Improvements in Notification Management:** The suggestions for detailed control of notifications, an admin notification dashboard, and notification logs are excellent. We plan to incorporate these improvements in future versions of the plugin.
    - **Integration with Third-party Email Tools:** We recognize the value of integrating with robust email platforms and will explore options to facilitate this.

### Commitment to the Community

We believe in the importance of listening to our community and are committed to providing regular updates as we progress in implementing these improvements. We encourage ongoing feedback and look forward to working together to make our plugin an even more valuable tool for all users.

### Follow-up

We plan to release an update to address the immediate issue in the coming weeks and follow up with incremental improvements over time. We will keep everyone informed through our official communication channels, including the plugin's changelog and announcements in the support forum.

Thank you again for your valuable feedback. Please do not hesitate to get in touch with us if you have further questions or suggestions.

Best regards,

Ariel Souza
PDR Development Team

**Comment by suzana-fqs** [comment]
## Follow-up on the Email Notification Issue

Firstly, I'd like to express my gratitude for the prompt response and the recent update to address the issue where email notifications were not being sent to administrators. It's great to see active development and support for this plugin.

### New Issue After Recent Update
However, after updating to the latest version, which includes the fix for sending notifications to administrators, we've encountered a new problem. The email notifications now *lack specific details* that were previously included and are crucial for our operations. Specifically, the emails are missing the following information:

- *Name*
- *Email*
- *Service Type*
- *Location*
- *Service Found*
- *Post ID*

This information is vital for service authors to understand who is interested in their offerings and to enable meaningful follow-up interactions.

### Expected Behavior
The expected behavior was that, along with fixing the issue related to administrator notifications, the email notifications to service authors would continue to include all relevant details about the viewer's inquiry, as they did before.

### Current Behavior
As of the latest update, while the issue of emails not being sent to administrators has been resolved, the emails have now become too generic and are missing critical details as listed above.

### Impact
The absence of this information diminishes the value of the email notifications, as it impedes service authors' ability to engage effectively with potential clients or interested parties. It directly affects our ability to follow up on leads and inquiries, which is a cornerstone of our platform's utility and effectiveness.

### Request for Resolution
Could you please look into reintroducing these details into the email notifications? Ensuring that email notifications contain comprehensive information about the inquiries is essential for the functionality and value provided by the plugin.

Thank you once again for your continued support and for addressing these issues. We look forward to the resolution and further improvements.
